// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_oa.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public final class AlarmHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements AlarmHandlerPrx
{
    private static final String __onAlarm_name = "onAlarm";

    public void onAlarm(AlarmMessage[] msglist)
    {
        onAlarm(msglist, null, false);
    }

    public void onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx)
    {
        onAlarm(msglist, __ctx, true);
    }

    private void onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "onAlarm", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _AlarmHandlerDel __del = (_AlarmHandlerDel)__delBase;
                    __del.onAlarm(msglist, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist)
    {
        return begin_onAlarm(msglist, null, false, null);
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx)
    {
        return begin_onAlarm(msglist, __ctx, true, null);
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, Ice.Callback __cb)
    {
        return begin_onAlarm(msglist, null, false, __cb);
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_onAlarm(msglist, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, Callback_AlarmHandler_onAlarm __cb)
    {
        return begin_onAlarm(msglist, null, false, __cb);
    }

    public Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx, Callback_AlarmHandler_onAlarm __cb)
    {
        return begin_onAlarm(msglist, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_onAlarm(AlarmMessage[] msglist, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __onAlarm_name, __cb);
        try
        {
            __result.__prepare(__onAlarm_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            AlarmListHelper.write(__os, msglist);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_onAlarm(Ice.AsyncResult __result)
    {
        __end(__result, __onAlarm_name);
    }

    private static final String __onChangedSchedule_name = "onChangedSchedule";

    public void onChangedSchedule(ScheduleMessage[] slist)
    {
        onChangedSchedule(slist, null, false);
    }

    public void onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx)
    {
        onChangedSchedule(slist, __ctx, true);
    }

    private void onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "onChangedSchedule", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _AlarmHandlerDel __del = (_AlarmHandlerDel)__delBase;
                    __del.onChangedSchedule(slist, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist)
    {
        return begin_onChangedSchedule(slist, null, false, null);
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx)
    {
        return begin_onChangedSchedule(slist, __ctx, true, null);
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, Ice.Callback __cb)
    {
        return begin_onChangedSchedule(slist, null, false, __cb);
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_onChangedSchedule(slist, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, Callback_AlarmHandler_onChangedSchedule __cb)
    {
        return begin_onChangedSchedule(slist, null, false, __cb);
    }

    public Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx, Callback_AlarmHandler_onChangedSchedule __cb)
    {
        return begin_onChangedSchedule(slist, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_onChangedSchedule(ScheduleMessage[] slist, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __onChangedSchedule_name, __cb);
        try
        {
            __result.__prepare(__onChangedSchedule_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            ScheduleListHelper.write(__os, slist);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_onChangedSchedule(Ice.AsyncResult __result)
    {
        __end(__result, __onChangedSchedule_name);
    }

    public static AlarmHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmHandlerPrx)
            {
                __d = (AlarmHandlerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static AlarmHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmHandlerPrx)
            {
                __d = (AlarmHandlerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static AlarmHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static AlarmHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static AlarmHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmHandlerPrx)
            {
                __d = (AlarmHandlerPrx)__obj;
            }
            else
            {
                AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static AlarmHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        AlarmHandlerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            AlarmHandlerPrxHelper __h = new AlarmHandlerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::AlarmHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _AlarmHandlerDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _AlarmHandlerDelD();
    }

    public static void __write(IceInternal.BasicStream __os, AlarmHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static AlarmHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            AlarmHandlerPrxHelper result = new AlarmHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
