// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_oa.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public enum AlarmPriority implements java.io.Serializable
{
    
    ALM_PRI_EMERGENCY(1),
    
    ALM_PRI_IMPORTTANT(2),
    
    ALM_PRI_NORMAL(3),
    
    ALM_PRI_PROMPT(4),
    
    ALM_PRI_EVENT(5);

    public int
    value()
    {
        return __value;
    }

    public static AlarmPriority
    valueOf(int __v)
    {
        switch(__v)
        {
        case 1:
            return ALM_PRI_EMERGENCY;
        case 2:
            return ALM_PRI_IMPORTTANT;
        case 3:
            return ALM_PRI_NORMAL;
        case 4:
            return ALM_PRI_PROMPT;
        case 5:
            return ALM_PRI_EVENT;
        }
        return null;
    }

    private
    AlarmPriority(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 5);
    }

    public static AlarmPriority
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(5);
        return __validate(__v);
    }

    private static AlarmPriority
    __validate(int __v)
    {
        final AlarmPriority __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
