// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_oa.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public class AlarmMessage implements Cloneable, java.io.Serializable
{
    public String groupname;

    public byte appsysid;

    public byte priority;

    public byte aoj;

    public String devicekey;

    public int devicetype;

    public int datetime;

    public int millisecond;

    public String text;

    public String classname;

    public String userattr1;

    public String userattr2;

    public String userattr3;

    public String userattr4;

    public AlarmMessage()
    {
    }

    public AlarmMessage(String groupname, byte appsysid, byte priority, byte aoj, String devicekey, int devicetype, int datetime, int millisecond, String text, String classname, String userattr1, String userattr2, String userattr3, String userattr4)
    {
        this.groupname = groupname;
        this.appsysid = appsysid;
        this.priority = priority;
        this.aoj = aoj;
        this.devicekey = devicekey;
        this.devicetype = devicetype;
        this.datetime = datetime;
        this.millisecond = millisecond;
        this.text = text;
        this.classname = classname;
        this.userattr1 = userattr1;
        this.userattr2 = userattr2;
        this.userattr3 = userattr3;
        this.userattr4 = userattr4;
    }

    public boolean
    equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AlarmMessage _r = null;
        if(rhs instanceof AlarmMessage)
        {
            _r = (AlarmMessage)rhs;
        }

        if(_r != null)
        {
            if(groupname != _r.groupname)
            {
                if(groupname == null || _r.groupname == null || !groupname.equals(_r.groupname))
                {
                    return false;
                }
            }
            if(appsysid != _r.appsysid)
            {
                return false;
            }
            if(priority != _r.priority)
            {
                return false;
            }
            if(aoj != _r.aoj)
            {
                return false;
            }
            if(devicekey != _r.devicekey)
            {
                if(devicekey == null || _r.devicekey == null || !devicekey.equals(_r.devicekey))
                {
                    return false;
                }
            }
            if(devicetype != _r.devicetype)
            {
                return false;
            }
            if(datetime != _r.datetime)
            {
                return false;
            }
            if(millisecond != _r.millisecond)
            {
                return false;
            }
            if(text != _r.text)
            {
                if(text == null || _r.text == null || !text.equals(_r.text))
                {
                    return false;
                }
            }
            if(classname != _r.classname)
            {
                if(classname == null || _r.classname == null || !classname.equals(_r.classname))
                {
                    return false;
                }
            }
            if(userattr1 != _r.userattr1)
            {
                if(userattr1 == null || _r.userattr1 == null || !userattr1.equals(_r.userattr1))
                {
                    return false;
                }
            }
            if(userattr2 != _r.userattr2)
            {
                if(userattr2 == null || _r.userattr2 == null || !userattr2.equals(_r.userattr2))
                {
                    return false;
                }
            }
            if(userattr3 != _r.userattr3)
            {
                if(userattr3 == null || _r.userattr3 == null || !userattr3.equals(_r.userattr3))
                {
                    return false;
                }
            }
            if(userattr4 != _r.userattr4)
            {
                if(userattr4 == null || _r.userattr4 == null || !userattr4.equals(_r.userattr4))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SSIP::AlarmMessage");
        __h = IceInternal.HashUtil.hashAdd(__h, groupname);
        __h = IceInternal.HashUtil.hashAdd(__h, appsysid);
        __h = IceInternal.HashUtil.hashAdd(__h, priority);
        __h = IceInternal.HashUtil.hashAdd(__h, aoj);
        __h = IceInternal.HashUtil.hashAdd(__h, devicekey);
        __h = IceInternal.HashUtil.hashAdd(__h, devicetype);
        __h = IceInternal.HashUtil.hashAdd(__h, datetime);
        __h = IceInternal.HashUtil.hashAdd(__h, millisecond);
        __h = IceInternal.HashUtil.hashAdd(__h, text);
        __h = IceInternal.HashUtil.hashAdd(__h, classname);
        __h = IceInternal.HashUtil.hashAdd(__h, userattr1);
        __h = IceInternal.HashUtil.hashAdd(__h, userattr2);
        __h = IceInternal.HashUtil.hashAdd(__h, userattr3);
        __h = IceInternal.HashUtil.hashAdd(__h, userattr4);
        return __h;
    }

    public Object
    clone()
    {
        Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(groupname);
        __os.writeByte(appsysid);
        __os.writeByte(priority);
        __os.writeByte(aoj);
        __os.writeString(devicekey);
        __os.writeInt(devicetype);
        __os.writeInt(datetime);
        __os.writeInt(millisecond);
        __os.writeString(text);
        __os.writeString(classname);
        __os.writeString(userattr1);
        __os.writeString(userattr2);
        __os.writeString(userattr3);
        __os.writeString(userattr4);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        groupname = __is.readString();
        appsysid = __is.readByte();
        priority = __is.readByte();
        aoj = __is.readByte();
        devicekey = __is.readString();
        devicetype = __is.readInt();
        datetime = __is.readInt();
        millisecond = __is.readInt();
        text = __is.readString();
        classname = __is.readString();
        userattr1 = __is.readString();
        userattr2 = __is.readString();
        userattr3 = __is.readString();
        userattr4 = __is.readString();
    }

    public static final long serialVersionUID = 1489753042L;
}
