// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ssip_oa.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SSIP;

public final class AlarmServicePrxHelper extends Ice.ObjectPrxHelperBase implements AlarmServicePrx
{
    private static final String __initAlarmHandler_name = "initAlarmHandler";

    public void initAlarmHandler(AlarmHandlerPrx proxy)
    {
        initAlarmHandler(proxy, null, false);
    }

    public void initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx)
    {
        initAlarmHandler(proxy, __ctx, true);
    }

    private void initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "initAlarmHandler", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _AlarmServiceDel __del = (_AlarmServiceDel)__delBase;
                    __del.initAlarmHandler(proxy, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy)
    {
        return begin_initAlarmHandler(proxy, null, false, null);
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx)
    {
        return begin_initAlarmHandler(proxy, __ctx, true, null);
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, Ice.Callback __cb)
    {
        return begin_initAlarmHandler(proxy, null, false, __cb);
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_initAlarmHandler(proxy, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, Callback_AlarmService_initAlarmHandler __cb)
    {
        return begin_initAlarmHandler(proxy, null, false, __cb);
    }

    public Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx, Callback_AlarmService_initAlarmHandler __cb)
    {
        return begin_initAlarmHandler(proxy, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_initAlarmHandler(AlarmHandlerPrx proxy, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __initAlarmHandler_name, __cb);
        try
        {
            __result.__prepare(__initAlarmHandler_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            AlarmHandlerPrxHelper.__write(__os, proxy);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_initAlarmHandler(Ice.AsyncResult __result)
    {
        __end(__result, __initAlarmHandler_name);
    }

    public static AlarmServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmServicePrx)
            {
                __d = (AlarmServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static AlarmServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmServicePrx)
            {
                __d = (AlarmServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static AlarmServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static AlarmServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static AlarmServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof AlarmServicePrx)
            {
                __d = (AlarmServicePrx)__obj;
            }
            else
            {
                AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static AlarmServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        AlarmServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            AlarmServicePrxHelper __h = new AlarmServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SSIP::AlarmService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _AlarmServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _AlarmServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, AlarmServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static AlarmServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            AlarmServicePrxHelper result = new AlarmServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
